name: grpc_stream_example
description: An example CLI application demonstrating the erroneous behavior of gRPC streams in Dart.
version: 1.0.0

environment:
  sdk: ^3.5.2

dependencies:
  grpc: ^4.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
